# Default values for xavier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: grpc-token-issuer
env: production
maxReplicas: 10
cpuUsage: 60

image:
  registry: gcr.io/nindoo-214818
  name: grpc-token-issuer
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  portName: http

environment: {}

resources:
  requests:
    cpu: 250m
