apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.image.tag }}
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.image.tag }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_MONGODB_DBNAME
              value: {{ default "xavier" .Values.environment.DATABASE_MONGODB_DBNAME | quote }}
            - name: JWT_PRIVATE_KEY_BASE64
              value: {{ required "You must set environment.JWT_PRIVATE_KEY_BASE64" .Values.environment.JWT_PRIVATE_KEY_BASE64 | quote }}
            - name: SERVER_BIND_PORT
              value: {{ default "3000" .Values.environment.SERVER_BIND_PORT | quote }}
            - name: SERVER_BIND_ADDRESS
              value: {{ default "0.0.0.0" .Values.environment.SERVER_BIND_ADDRESS | quote }}
            - name: JWT_ISSUER
              value: {{ default "grpc-token-issuer" .Values.environment.JWT_ISSUER | quote }}
            - name: JWT_AUDIENCE
              value: {{ default "grpc-token-issuer" .Values.environment.JWT_AUDIENCE | quote }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: grc-credentials
